# Generated by Django 4.2.30 on 2026-04-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_vehicles',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_washroom_passes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='wants_electricity',
            field=models.BooleanField(default=False),
        ),
    ]
