# Generated by Django 4.2.30 on 2026-04-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalised', 'Finalised'), ('paid', 'Paid')], default='draft', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='PaySlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nis_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('health_surcharge', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('other_deductions_notes', models.TextField(blank=True)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nis_rate_used', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('health_surcharge_applied', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pay_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='payroll.payperiod')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='workers.worker')),
            ],
            options={
                'ordering': ['pay_period', 'worker'],
                'unique_together': {('pay_period', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='HoursEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.TimeField(blank=True, null=True)),
                ('clock_out', models.TimeField(blank=True, null=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, help_text='Can be entered manually or auto-calculated from clock_in / clock_out.', max_digits=5)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours_entries', to='workers.worker')),
            ],
            options={
                'ordering': ['-date', 'worker'],
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
